   module.exports = [
    { name: 'Rem demonio', file: 'rem demonio.jpg', anime: 'Re zero' },
    { name: 'Ainz ooal gown', file: 'ainz ooal gown.jpg', anime: 'Overlord' },
    { name: 'Goblin slayer', file: 'goblin slayer.jpg', anime: 'Goblin slayer' },
    { name: 'Saitama', file: 'saitama.jpg', anime: 'One punch man' },
    { name: 'Kaede y Suzu', file: 'kaede y suzu.jpg', anime: 'Kaede to suzu the animation' },
    { name: 'Ryuko matoi', file: 'ryuko matoi.jpg', anime: 'Kill la kill' },
    { name: 'Saki nikaido', file: 'saki nikaido.jpg', anime: 'Zombieland saga' },
    { name: 'Saber', file: 'saber.jpg', anime: 'Fate' },
    { name: '2B Nier', file: '2b nier.jpg', anime: 'Nier Automata' },
    { name: 'Ju fufu', file: 'ju fufu.jpg', anime: 'Zenless zone zero' },
    { name: 'Nico yazawa', file: 'nico yazawa.jpg', anime: 'Love live' },
    { name: 'Eriko', file: 'eriko.jpg', anime: 'Princess connect' },
    { name: 'Kokkoro', file: 'kokkoro.jpg', anime: 'Princess connect' },
    { name: 'Shinobu', file: 'shinobu.jpg', anime: 'Princess connect' },
    { name: 'Pecorine', file: 'pecorine.jpg', anime: 'Princess connect' },
    { name: 'Luna', file: 'luna.jpg', anime: 'Princess connect' },
    { name: 'Reinhard Van Astrea', file: 'reinhard van astrea.jpg', anime: 'Re zero' },
    { name: 'Flugel El Gran Sabio', file: 'flugel el gran sabio.jpg', anime: 'Re zero' },
    { name: 'Nova', file: 'nova.jpg', anime: 'Metal slug attack' },
    { name: 'Ai hoshino', file: 'ai hoshino.jpg', anime: 'Oshi no ko' },
    { name: 'Aisaka Taiga', file: 'aisaka taiga.jpg', anime: 'Toradora' },
    { name: 'Lucy', file: 'Lucy.jpg', anime: 'Cyberpunk' },
    { name: 'Kaoruku waguri', file: 'kaoruku waguri.jpg', anime: 'Hana wa rin to saku' },
    { name: 'Miia', file: 'miia.jpg',anime: 'Monster musume' },
    { name: 'Agnes Tachyon', file: 'Agnes Tachyon.jpg', anime: 'Uma musume' },
    { name: 'Gawr Gura', file: 'Gawr Gura.jpg', anime: 'Streamer' },
    { name: 'Kurumi Tokisaki', file: 'Kurumi Tokisaki.jpg', anime: 'Date a live' },
    { name: 'Kasane Teto', file: 'Kasane Teto.jpg', anime: 'UTAU' },
    { name: 'Shizuka Hiratsuka', file: 'Shizuka Hiratsuka.jpg', anime: 'Yahari ore no seishun love come wa machigatteiru' },
    { name: 'Ryuuge Kisaki', file: 'Ryuuge Kisaki.jpg', anime: 'Blue archive' },
    { name: 'Nozomi y Hikari', file: 'Nozomi y Hikari.jpg', anime: 'Blue archive' },
    { name: 'Junko Enoshima', file: 'Junko Enoshima.jpg', anime: 'Danganropa' },
    { name: 'Ueno-san', file: 'Ueno-san.jpg', anime: 'Ueno san wa bukiyo' },
    { name: 'Kururu Tepes', file: 'Kururu Tepes.jpg', anime: 'Owari no seraph' },
    { name: 'Senko san', file: 'Senko san.jpg', anime: 'sewayaki kitsune no senko san' },
    { name: 'Maple', file: 'Maple.jpg', anime: 'Itai no wa iya nano de bogyoryoku ni kyofuri shitai to omoimasu' },
    { name: 'Laffey', file: 'Laffey.jpg', anime: 'Azur lane' },
    { name: 'Ye shunguan', file: 'Ye shunguan.jpg', anime: 'Zenless zone zero' },
    { name: 'Mai Sakurajima', file: 'Mai Sakurajima.jpg', anime: 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai'},
    { name: 'Bot', file: 'bot.jpg', anime: 'The sonrisas'},

    ]
